### ISSUE TITLE
NoMethodError for `relativize_urls`

### ISSUE THREAD

**Issue by sgroth** [untra/polyglot#40]
I am getting the following error, using Jekyll 3.3.0 and Polyglot 1.2.0:

`/Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:120:in `relativize_urls`: undefined method `gsub!' for nil:NilClass (NoMethodError)`

Any idea what could be causing this?

Running --trace results in:

```
/Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:120:in `relativize_urls': undefined method `gsub!' for nil:NilClass (NoMethodError)
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:91:in `block in process_documents'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:90:in `each'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:90:in `process_documents'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/hooks/process.rb:3:in `block in <top (required)>'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/hooks.rb:98:in `block in trigger'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/hooks.rb:97:in `each'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/hooks.rb:97:in `trigger'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:193:in `render'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:69:in `process'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:66:in `process_active_language'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:57:in `process_language'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:39:in `block in process'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:38:in `each'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:38:in `process'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/command.rb:26:in `process_site'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:63:in `build'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/exe/jekyll:13:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `load'
	from /Users/user/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by untra** [comment]
Full disclosure: I actually haven't tested polyglot with Jekyll 3.3.0 yet. It's fairly new.

The error is being thrown from [here](https://github.com/untra/polyglot/blob/master/lib/jekyll/polyglot/patches/jekyll/site.rb#L120). Relativize urls is being called on a document with a `null` output. Document output's should not be `null` when this hook is called. If the jekyll team changed things

Any chance your jekyll project is accessible and on github? I'd be happy to clone it down and debug it further.
